name: "Discord BreadBot"
description: "Discord BreadBot"
version: "1.1.1"
slug: "discord_breadbot"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5987/tcp: 5987
